name: Android CI

on:
  push: 
    branches: 
      - "master"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Decrypt signing key
      env:
        RELEASE_KEYSTORE_SECRET: ${{ secrets.RELEASE_KEYSTORE_SECRET }}
        RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      run: . decrypt_key.sh > ./android/app/release-keystore.jks
    
    - name: Generate key.properties
      env:
        KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
      run: printf "$KEY_PROPERTIES" > ./android/key.properties
    
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
      
    - name: Get project dependencies
      run: flutter pub get
    
    - name: Update app icon
      run: flutter pub run flutter_launcher_icons
    
    - name: Build apk
      run: flutter build apk --split-per-abi --obfuscate --split-debug-info=./lib
    
    - name: Create a new draft
      uses: ncipollo/release-action@v1
      with: 
        allowUpdates: true
        artifacts: build/app/outputs/flutter-apk/*.apk
        token: ${{ secrets.RELEASE_TOKEN }}
        tag: draft