on:
  push: 
    branch: 
      - master
jobs:
  build-and-test:
    name: Build apk release
    runs-on: ubuntu-latest
    steps:
    - name: Actions/checkout
      uses: actions/checkout@v3
    
    - name: Decrypt signing key
      env:
        RELEASE_KEYSTORE_SECRET: ${{ secrets.RELEASE_KEYSTORE_SECRET }}
        RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      run: . decrypt_key.sh > ./android/app/release-keystore.jks
    
    - name: Generate key.properties
      env:
        KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
      run: printf "$KEY_PROPERTIES" > ./android/key.properties
    
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    - name: init Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
      
    - name: pub get dependencies
      run: flutter pub get
    
    - name: Build apk
      run: flutter build apk --split-per-abi